//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductDetail
    {
        public int Product_ID { get; set; }
        [Display(Name="Product Name")]
        [Required]
        public string Product_Name { get; set; }
        [Display(Name = "Product Price")]
        [Required]
        public int Product_Price { get; set; }
    }
}
